# Generated by Django 2.2.4 on 2019-08-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SewageSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleNumber', models.CharField(max_length=120)),
                ('depth', models.CharField(choices=[('sur', 'Surface'), ('bot', 'Bottom')], default='sur', max_length=3)),
                ('sampleLabel', models.IntegerField()),
                ('sampleStation', models.CharField(max_length=10)),
                ('sampleGPS_N', models.CharField(max_length=25)),
                ('sampleGPS_E', models.CharField(max_length=25)),
                ('collectionTiming', models.DateTimeField(blank=True)),
                ('sampleVolume', models.FloatField()),
                ('sampleProcessed', models.BooleanField()),
                ('processedVolume', models.FloatField()),
                ('remainingVolume', models.FloatField()),
                ('sampleKit', models.CharField(max_length=120)),
                ('sampleDepth', models.FloatField()),
                ('sampleO2Level', models.FloatField()),
                ('sampleTemp', models.FloatField()),
                ('sampleSalinity', models.FloatField()),
                ('airTempInShade', models.FloatField()),
                ('cloudCover', models.CharField(max_length=120)),
                ('windSpeed', models.FloatField()),
                ('seaColor', models.CharField(max_length=120)),
                ('tide', models.CharField(choices=[('ltid', 'Low Tide'), ('mtid', 'Mid Tide'), ('htid', 'High Tide')], default='ltid', max_length=4)),
                ('RH', models.FloatField()),
                ('windDirection', models.CharField(max_length=2)),
                ('baromPressure', models.FloatField()),
                ('waveHeight', models.FloatField()),
                ('SucchiDisc', models.FloatField()),
                ('TotalDepth', models.FloatField()),
                ('param9', models.IntegerField()),
                ('param10', models.IntegerField()),
            ],
        ),
    ]
