# Generated by Django 2.2.4 on 2019-08-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm120k_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sewagesample',
            name='param10',
        ),
        migrations.RemoveField(
            model_name='sewagesample',
            name='param9',
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='RH',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='SucchiDisc',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='TotalDepth',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='airTempInShade',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='baromPressure',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='cloudCover',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='processedVolume',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='remainingVolume',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleDepth',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleKit',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleLabel',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleO2Level',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleSalinity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleTemp',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleVolume',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='seaColor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='waveHeight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='windDirection',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='windSpeed',
            field=models.FloatField(blank=True),
        ),
    ]
