# Generated by Django 2.2.4 on 2019-08-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm120k_db', '0002_auto_20190827_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleGPS_E',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleGPS_N',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleLabel',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleStation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
