# Generated by Django 2.2.4 on 2019-08-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm120k_db', '0003_auto_20190827_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewagesample',
            name='Notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sewagesample',
            name='storage',
            field=models.CharField(choices=[('Room Temperature', 'Room Temperature'), ('4 Degrees', '4 Degrees'), ('-20 Degrees', 'Minus 20 Degrees'), ('-80 Degrees', 'Minus 80 Degrees')], default='4 Degrees', max_length=20),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='depth',
            field=models.CharField(choices=[('Surface', 'Surface'), ('Bottom', 'Bottom')], default='Surface', max_length=7),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleKit',
            field=models.CharField(choices=[('Qiagen', 'Qiagen'), ('MN', 'MN'), ('Mobio', 'Mobio'), ('Other', 'Other')], default='Qiagen', max_length=6),
        ),
        migrations.AlterField(
            model_name='sewagesample',
            name='sampleStation',
            field=models.CharField(choices=[('18', '18'), ('A', 'A'), ('K6', 'K6')], default=18, max_length=2),
        ),
    ]
