# Generated by Django 2.2.4 on 2019-08-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm120k_db', '0005_auto_20190829_0939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SewageSample',
            new_name='SeawaterSample',
        ),
    ]
