# Generated by Django 2.2.4 on 2019-12-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm120k_db', '0006_auto_20190830_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seawatersample',
            name='sampleKit',
            field=models.CharField(choices=[('Qiagen DNeasy Animal and Tissue Kit', 'Qiagen DNeasy Animal and Tissue Kit'), ('Macherey-Nagel Nucleospin Kit', 'Macherey-Nagel Nucleospin Kit'), ('MO BIO PowerSoil DNA Isolation Kit', 'MO BIO PowerSoil DNA Isolation Kit'), ('Other', 'Other')], default='Qiagen DNeasy Animal and Tissue Kit', max_length=6),
        ),
        migrations.AlterField(
            model_name='seawatersample',
            name='storage',
            field=models.CharField(choices=[('Room Temperature', 'Room Temperature'), ('4 Degrees', '4 Degrees Celsius'), ('-20 Degrees', 'Minus 20 Degrees Celsius'), ('-80 Degrees', 'Minus 80 Degrees Celsius')], default='4 Degrees', max_length=20),
        ),
    ]
