# Generated by Django 2.2.4 on 2020-01-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm120k_db', '0008_auto_20200130_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seawatersample',
            old_name='SucchiDisc',
            new_name='secchiDisk',
        ),
    ]
