# Generated by Django 2.2.4 on 2020-02-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm120k_db', '0009_auto_20200130_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seawatersample',
            name='F_readfile',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='seawatersample',
            name='R_readfile',
            field=models.URLField(),
        ),
    ]
