# Generated by Django 2.2.4 on 2020-02-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm120k_db', '0010_auto_20200203_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seawatersample',
            old_name='sampleKit',
            new_name='extractionKit',
        ),
    ]
